baseurl = "http://mmbros.github.io"
languageCode = "it-IT"
title = "mmbros homepage"
pluralizeListTitles = false
builddrafts = true
theme = "mmbase"
# [permalinks]
# eventi = /:year/:month/:day/:slug/

[taxonomies]
  category = "categories"
  tag = "tags"
